% Decide which files to include in release
copyfile("..\model\changelog.txt", "model_changelog.txt")

files = [
	"adaptation.c",...
	"compile_mex.m",...
	"complex.c",...
	"complex.hpp",...
	"demo.m",...
	"ffGn.m",...
	"model.h",...
	"model.c",...
	"README.txt",...
	"sfie.c",...
	"sim_efferent_model.m",...
	"sim_efferent_model_mex.c",...
	"model_changelog.txt"...
];

% Create filename
filename = strcat("efferent_model", "_", string(datetime("today", "Format", "yyyy-MM-dd")), ".zip");

% Create zip
zip(filename, files);